apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: bold-services
  name: boldreports-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    # tls:
      # httpsRedirect: true
    hosts:
    - "*"
    # - example.com
  # - port:
      # number: 443
      # name: https
      # protocol: HTTPS
    # tls:
      # mode: SIMPLE
      # credentialName: boldreports-tls
    # hosts:
    # - example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: bold-services
  name: boldreports-virtual-service
spec:
  hosts:
  - "*"
  # - example.com
  gateways:
  - boldreports-gateway
  http:
  - match:
    - uri:
        prefix: /reporting/reportservice
    route:
    - destination:
        port:
          number: 6553
        host: reports-reportservice-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting/api
    route:
    - destination:
        port:
          number: 6551
        host: reports-api-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting/jobs
    route:
    - destination:
        port:
          number: 6552
        host: reports-jobs-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting/viewer
    route:
    - destination:
        port:
          number: 6554
        host: reports-viewer-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting
    route:
    - destination:
        port:
          number: 6550
        host: reports-web-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        port:
          number: 6001
        host: id-api-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /ums
    route:
    - destination:
        port:
          number: 6002
        host: id-ums-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 6000
        host: id-web-service.bold-services.svc.cluster.local
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream